elyra-ai/pipeline-schemas

CONTRIBUTING.md
code-of-conduct.md

Governance updates

---

common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json

Add op property to the model node definition.

---

common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json

Add link ID to links object

---

common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json

Change newly added link_type for links to type_attr

---

scripts/publish_modules.sh

Tag published builds

---

scripts/tagBuild.sh

Add missing file

---

scripts/publish_modules.sh

Fix typo in version number

---

common-pipeline/operators/uihints-v3-schema.json

Add new controls to schema

---

common-pipeline/operators/operator-v3-schema.json

#24 Add type property to complex type definition

---

common-pipeline/pipeline-connection/pipeline-connection-v3-schema.json

#28 Incorrect reference to app_data_def in connections schema

---

common-pipeline/datarecord-metadata/datarecord-metadata-v3-schema.json
common-pipeline/pipeline-connection/pipeline-connection-v3-schema.json
common-pipeline/pipeline-flow/pipeline-flow-ui-v3-schema.json
common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json

Improve schema file so that it could be validated by open source tools

---

common-pipeline/pipeline-flow/pipeline-flow-ui-v3-schema.json

#34 Fix app_data attribute types in pipeline-flow-ui-schema.json

---

common-canvas/form/form-v4-schema.json

subControls support controls

---

common-canvas/form/form-v4-schema.json
common-pipeline/operators/uihints-v3-schema.json

#40 add readonlyTable control

---

.eslintrc.js
.gitignore
.npmignore
.npmrc
.travis.yml
CONTRIBUTING.md
README.md
code-of-conduct.md
common-canvas/README.md
common-pipeline/pipeline-flow/upgrade/upgrade-flow.js
scripts/publish_modules.sh
scripts/tagBuild.sh

Attribute copyright notice to Elyra Authors

---

common-pipeline/pipeline-flow/pipeline-flow-ui-v3-schema.json

#43 Extend zoom function to store translation amounts

---

common-pipeline/pipeline-flow/pipeline-flow-ui-v3-schema.json

#45 Comments should not be restricted to positive coordinates

---

.github/workflows/publish.yml
scripts/publish_modules.sh
scripts/tagBuild.sh

Mhoward move GitHub actions

---

.github/workflows/publish.yml
scripts/publish_modules.sh
scripts/tagBuild.sh

#48 move GitHub actions

---

common-canvas/form/form-v4-schema.json

Fixes https://github.com/elyra-ai/pipeline-schemas/issues/53
it.
(d) …

#53 Update Form schema to include icon and heading properties

---

common-canvas/form/form-v4-schema.json
common-pipeline/operators/uihints-v3-schema.json

#55 add 'custom_value_allowed' to uihints

---

common-canvas/form/form-v4-schema.json
common-pipeline/operators/uihints-v3-schema.json

#57 properties panels and controls should have the ability to specify a class name

---

common-canvas/parameter-defs/parameter-defs-v3-schema.json
common-pipeline/datarecord-metadata/datarecord-metadata-v3-schema.json
common-pipeline/operators/conditions-v3-schema.json
common-pipeline/operators/operator-v3-schema.json
common-pipeline/operators/uihints-v3-schema.json

#59 fix schema for parameter definitions

---

common-canvas/form/form-v4-schema.json
common-pipeline/operators/uihints-v3-schema.json

#61 new multiselect control in properties

---

common-pipeline/pipeline-flow/pipeline-flow-ui-v3-schema.json
common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json

#64 Descriptions in pipeline flow should be deprecated

---

common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json

#36 Binding nodes should have either required outputs or inputs

---

common-canvas/form/form-v4-schema.json

Update schema to be consistant and match what is expected in code

---

common-pipeline/parameters/parameters-v3-schema.json

This is pull request for https://github.com/elyra-ai/pipeline-schemas/issues/72 
person who certified (a), (b) or (c) and I have …

required property for parameter should be name and type

---

common-pipeline/pipeline-flow/pipeline-flow-v1-schema.json
common-pipeline/pipeline-flow/pipeline-flow-v2-schema.json
common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json

#74 Add http URL to json_schema enum in pipeline flow schema

---

common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json

#77 Support alternative output from exit binding node

---

common-pipeline/operators/uihints-v3-schema.json

#84 Add open attribute to groups

---

common-pipeline/datarecord-metadata/datarecord-metadata-v3-schema.json

#90 Updated values array items type

---

common-pipeline/operators/uihints-v3-schema.json

#93 Added new config option "tooltip_direction" for action images

---

common-pipeline/operators/uihints-v3-schema.json

custom table buttons

---

common-pipeline/operators/uihints-v3-schema.json

#95 custom table buttons - carbon_icon is a string

---

common-pipeline/operators/uihints-v3-schema.json

#97 Added 'resizable' config option in parameter_definition

---

common-pipeline/operators/uihints-v3-schema.json

#99 Support adding a link in properties tooltips

---

common-pipeline/pipeline-flow/pipeline-flow-ui-v3-schema.json

#103 Support resize variables for 'resize nodes' feature

---

common-pipeline/pipeline-flow/pipeline-flow-ui-v3-schema.json

#103 Support resize variable for 'resize ndoes' feature (Part 2)

---

common-pipeline/datarecord-metadata/datarecord-metadata-v3-schema.json

#101 Support strings in expression builder min and max range

---

common-pipeline/operators/uihints-v3-schema.json

#106 New config option for action buttons kind and size

---

common-pipeline/pipeline-flow/pipeline-flow-ui-v3-schema.json

#108 Remove limitations on zoom scale (k) value

---

common-pipeline/pipeline-flow/pipeline-flow-ui-v3-schema.json

#110 Document app_data.ui_data.sub_pipelines field

---

.github/workflows/publish.yml
CONTRIBUTING.md
README.md
code-of-conduct.md
common-pipeline/pipeline-flow/examples/pipeline-flow-v2-external-subflow-example.json
package.json
scripts/publish_modules.sh

#112 Rename master to main

---

common-pipeline/pipeline-connection/pipeline-connection-v3-schema.json

#114 Add space_ref to connection schema

---

common-pipeline/operators/uihints-v3-schema.json

#3347 Add toggle control to use in Modeler modeling node overrides

---

common-canvas/expression/function-list-v3-schema.json

#117 Added return_type_label in expression function info

---

common-pipeline/operators/uihints-v3-schema.json
package.json

#120 add tearsheet support

---

common-canvas/form/form-v4-schema.json
common-pipeline/operators/uihints-v3-schema.json

#121 Added SQL in expression editor supported languages

---

common-canvas/expression/expression-info-v3-schema.json

#123 Support description in expression info table header

---

common-canvas/form/form-v4-schema.json
common-pipeline/operators/uihints-v3-schema.json

Schema changes for https://github.com/elyra-ai/canvas/pull/1407
closes #127 
person who certified (a), (b) or (c) and I have not …

#127 Schema changes for datepicker control

---

common-pipeline/operators/uihints-v3-schema.json

#131 Schema changes to support custom class for actions

---

.eslintrc.js
.github/workflows/publish.yml
.gitignore
.npmignore
.npmrc
CONTRIBUTING.md
README.md
code-of-conduct.md
common-canvas/README.md
common-pipeline/pipeline-flow/upgrade/upgrade-flow.js
scripts/publish_modules.sh
scripts/tagBuild.sh

Update Copyright year

---

common-pipeline/pipeline-flow/pipeline-flow-ui-v3-schema.json

#141 Support JSX object as node image

---

.eslintrc.js
.github/workflows/publish.yml
.gitignore
.npmignore
.npmrc
CONTRIBUTING.md
README.md
code-of-conduct.md
common-canvas/README.md
common-pipeline/pipeline-flow/upgrade/upgrade-flow.js
scripts/publish_modules.sh
scripts/tagBuild.sh

Update copyright to 2025

---

common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json

#151 Add 'deprecated' field to Link Definition description

---

common-pipeline/pipeline-flow/pipeline-flow-ui-v3-schema.json

#155 Make decoration_def anyOf instead of oneOf

---

scripts/generateTS.sh

Test with .bak

---

scripts/generateTS.sh

Escape chars

---

.github/workflows/build.yml
.github/workflows/publish.yml
scripts/generateTS.sh

Add build step for pipeline-schemas

---

.github/workflows/publish.yml

#166 Bump up node version in publish.yml

---

.github/workflows/build.yml
.github/workflows/publish.yml

#166 Bump up node version in publish.yml (part 2)

---

scripts/generateTS.sh

#166 Bump up node version in publish.yml (part 3)

---

scripts/generateTS.sh
scripts/publish_modules.sh

#166 Bump up node version in publish.yml (part 4)

---

scripts/generateTS.sh

#171 Explicitely export Typescript types

---

common-canvas/canvas-info/canvas-info-v3-schema.json
scripts/generateTS.sh

#177 Add extra properties to canvas info schema for typescript support

---

common-pipeline/operators/uihints-v3-schema.json

#175 New uihint 'should_filter_item'

---

common-canvas/canvas-info/canvas-info-v3-schema.json
scripts/generateTS.sh

#179 Ensure generated TS files handle readonly properties correctly

---

common-pipeline/operators/uihints-v3-schema.json

#181 Update pipeline-schema for custom actions in common-properties

---

common-pipeline/operators/uihints-v3-schema.json

#190 Add 'kind' to common properties custom table toolbar buttons
